FROM node:latest
# Create app directory
WORKDIR /app
# Install app dependencies
# Copy app files
COPY *.json ./
COPY server2.js .
COPY public ./public   
RUN npm install
#Expose port
EXPOSE 3002
#Start the app
CMD ["node", "server2.js" ]
#Use terminal to start app
#CMD ["/bin/bash"]