# Use Node image
FROM node:latest

# Create app directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy compiled JS + public files
## .ts to .js
# COPY dist ./dist
COPY public ./public

# Expose port
EXPOSE 3002

# Run the app
## .ts to .js
CMD ["node", "dist/server.js"]
## .ts
#CMD ["npx", "ts-node", "server.ts"]
